<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Version>1.9.1</Version>
    <Authors>AVAM&amp;M contributors</Authors>
    <Product>AVAM&amp;M</Product>
    <Copyright>Copyright (c) 2026 AVAM&amp;M contributors (MIT)</Copyright>
    <AvaloniaVersion>11.3.22</AvaloniaVersion>
    <RepoRoot>$(MSBuildThisFileDirectory)</RepoRoot>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
</Project>
